#############################################################################
# Generated by PAGE version 4.17
# in conjunction with Tcl version 8.6
# Oct 14, 2018 10:20:34 PM CEST  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

vTcl:font:add_GUI_font TkDefaultFont \
"-family Helvetica -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkFixedFont \
"-family courier -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkMenuFont \
"-family Helvetica -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkTextFont \
"-family Helvetica -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top39
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top39
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top39 {base} {
    if {$base == ""} {
        set base .top39
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -relief sunken -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 591x588+479+202
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Pyxtal Main Controls"
    vTcl:DefineAlias "$top" "pyxtal_main" vTcl:Toplevel:WidgetProc "" 1
    labelframe $top.lab41 \
        -foreground black -text {Input Files} -background {#d9d9d9} \
        -height 245 -highlightcolor black -width 290 
    vTcl:DefineAlias "$top.lab41" "Labelframe2" vTcl:WidgetProc "pyxtal_main" 1
    set site_3_0 $top.lab41
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_3_0.scr42 \
        -background {#d9d9d9} -height 170 -highlightcolor black -width 276 
    vTcl:DefineAlias "$site_3_0.scr42" "Scrolledlistbox1" vTcl:WidgetProc "pyxtal_main" 1

    $site_3_0.scr42.01 configure -background white \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    button $site_3_0.but93 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Add Files} 
    vTcl:DefineAlias "$site_3_0.but93" "AddButton" vTcl:WidgetProc "pyxtal_main" 1
    button $site_3_0.but94 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Clear Files} 
    vTcl:DefineAlias "$site_3_0.but94" "ClearButton" vTcl:WidgetProc "pyxtal_main" 1
    place $site_3_0.scr42 \
        -in $site_3_0 -x 6 -y 70 -width 276 -relwidth 0 -height 170 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but93 \
        -in $site_3_0 -x 10 -y 30 -width 98 -height 33 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but94 \
        -in $site_3_0 -x 160 -y 30 -width 108 -height 33 -anchor nw \
        -bordermode ignore 
    button $top.but43 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Save Defaults} 
    vTcl:DefineAlias "$top.but43" "SaveDefButton" vTcl:WidgetProc "pyxtal_main" 1
    labelframe $top.lab48 \
        -foreground black -text {Input File Options} -background {#d9d9d9} \
        -height 295 -highlightcolor black -width 290 
    vTcl:DefineAlias "$top.lab48" "inputFrame" vTcl:WidgetProc "pyxtal_main" 1
    set site_3_0 $top.lab48
    radiobutton $site_3_0.rad41 \
        -activebackground {#d9d9d9} -activeforeground black -anchor w \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text {Image file} -value 1 -variable inFileType 
    vTcl:DefineAlias "$site_3_0.rad41" "imageRadio" vTcl:WidgetProc "pyxtal_main" 1
    radiobutton $site_3_0.rad42 \
        -activebackground {#d9d9d9} -activeforeground black -anchor w \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text {gsd assemblies} -value 3 -variable inFileType 
    vTcl:DefineAlias "$site_3_0.rad42" "gsdAssemRadio" vTcl:WidgetProc "pyxtal_main" 1
    radiobutton $site_3_0.rad43 \
        -activebackground {#d9d9d9} -activeforeground black -anchor w \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text {gsd particles} -value 2 -variable inFileType 
    vTcl:DefineAlias "$site_3_0.rad43" "gsdPartRadio" vTcl:WidgetProc "pyxtal_main" 1
    entry $site_3_0.ent44 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable spheresizestr 
    vTcl:DefineAlias "$site_3_0.ent44" "SphereEntry" vTcl:WidgetProc "pyxtal_main" 1
    label $site_3_0.lab45 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Sphere Size:} 
    vTcl:DefineAlias "$site_3_0.lab45" "SphereSizeLabel" vTcl:WidgetProc "pyxtal_main" 1
    label $site_3_0.lab53 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {of type:} 
    vTcl:DefineAlias "$site_3_0.lab53" "PartTypeLabel" vTcl:WidgetProc "pyxtal_main" 1
    entry $site_3_0.ent54 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent54" "PartTypeEntry" vTcl:WidgetProc "pyxtal_main" 1
    checkbutton $site_3_0.che67 \
        -activebackground {#d9d9d9} -activeforeground black -anchor w \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -offrelief sunken -text {Periodic Boundaries} \
        -variable periodBound 
    vTcl:DefineAlias "$site_3_0.che67" "PeriodicCheck" vTcl:WidgetProc "pyxtal_main" 1
    labelframe $site_3_0.lab82 \
        -foreground black -text frames -background {#d9d9d9} -height 75 \
        -width 270 
    vTcl:DefineAlias "$site_3_0.lab82" "framesframe" vTcl:WidgetProc "pyxtal_main" 1
    set site_4_0 $site_3_0.lab82
    entry $site_4_0.ent83 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent83" "fromEntry_18" vTcl:WidgetProc "pyxtal_main" 1
    label $site_4_0.lab84 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text From 
    vTcl:DefineAlias "$site_4_0.lab84" "framesLabel_14" vTcl:WidgetProc "pyxtal_main" 1
    label $site_4_0.lab85 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text to 
    vTcl:DefineAlias "$site_4_0.lab85" "framesLabel_15" vTcl:WidgetProc "pyxtal_main" 1
    entry $site_4_0.ent86 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent86" "toEntry" vTcl:WidgetProc "pyxtal_main" 1
    label $site_4_0.lab87 \
        -activebackground {#f9f9f9} -activeforeground black -anchor w \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text by 
    vTcl:DefineAlias "$site_4_0.lab87" "framesLabel_16" vTcl:WidgetProc "pyxtal_main" 1
    entry $site_4_0.ent88 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent88" "byEntry" vTcl:WidgetProc "pyxtal_main" 1
    place $site_4_0.ent83 \
        -in $site_4_0 -x 50 -y 30 -width 36 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab84 \
        -in $site_4_0 -x 10 -y 40 -width 38 -relwidth 0 -height 15 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab85 \
        -in $site_4_0 -x 100 -y 40 -width 38 -height 15 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent86 \
        -in $site_4_0 -x 130 -y 30 -width 36 -height 27 -anchor nw \
        -bordermode ignore 
    place $site_4_0.lab87 \
        -in $site_4_0 -x 190 -y 40 -width 38 -height 15 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent88 \
        -in $site_4_0 -x 220 -y 30 -width 36 -height 27 -anchor nw \
        -bordermode ignore 
    checkbutton $site_3_0.che92 \
        -activebackground {#d9d9d9} -activeforeground black -anchor w \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text {Spheres Dark} -variable che89 
    vTcl:DefineAlias "$site_3_0.che92" "DarkSphereCheck" vTcl:WidgetProc "pyxtal_main" 1
    place $site_3_0.rad41 \
        -in $site_3_0 -x 10 -y 30 -width 144 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad42 \
        -in $site_3_0 -x 10 -y 90 -width 159 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad43 \
        -in $site_3_0 -x 10 -y 60 -width 132 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent44 \
        -in $site_3_0 -x 130 -y 210 -width 66 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 27 -y 220 -width 98 -relwidth 0 -height 15 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 150 -y 90 -width 68 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent54 \
        -in $site_3_0 -x 210 -y 80 -width 66 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che67 \
        -in $site_3_0 -x 10 -y 250 -width 185 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab82 \
        -in $site_3_0 -x 10 -y 120 -width 270 -relwidth 0 -height 75 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che92 \
        -in $site_3_0 -x 150 -y 30 -width 135 -height 17 -anchor nw \
        -bordermode ignore 
    button $top.but40 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Load Defaults} 
    vTcl:DefineAlias "$top.but40" "LoadDefButton" vTcl:WidgetProc "pyxtal_main" 1
    labelframe $top.lab46 \
        -foreground black -text {Output File Options} -background {#d9d9d9} \
        -height 185 -highlightcolor black -width 260 
    vTcl:DefineAlias "$top.lab46" "outputFrame" vTcl:WidgetProc "pyxtal_main" 1
    set site_3_0 $top.lab46
    entry $site_3_0.ent44 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent44" "ImgSizeEntry" vTcl:WidgetProc "pyxtal_main" 1
    label $site_3_0.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Image size:} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label1_7" vTcl:WidgetProc "pyxtal_main" 1
    checkbutton $site_3_0.che68 \
        -activebackground {#d9d9d9} -activeforeground black -anchor w \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text {Image and Circles} -variable che64 
    vTcl:DefineAlias "$site_3_0.che68" "OutCirclesCheck" vTcl:WidgetProc "pyxtal_main" 1
    checkbutton $site_3_0.che69 \
        -activebackground {#d9d9d9} -activeforeground black -anchor w \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text Triangulation -variable che64 
    vTcl:DefineAlias "$site_3_0.che69" "OutTriangCheck" vTcl:WidgetProc "pyxtal_main" 1
    checkbutton $site_3_0.che70 \
        -activebackground {#d9d9d9} -activeforeground black -anchor w \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text {Image + angle + defects} -variable che64 
    vTcl:DefineAlias "$site_3_0.che70" "OutAllCheck" vTcl:WidgetProc "pyxtal_main" 1
    checkbutton $site_3_0.che91 \
        -activebackground {#d9d9d9} -activeforeground black -anchor w \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text mpeg -variable che89 
    vTcl:DefineAlias "$site_3_0.che91" "mpegCheck" vTcl:WidgetProc "pyxtal_main" 1
    place $site_3_0.ent44 \
        -in $site_3_0 -x 130 -y 110 -width 66 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 30 -y 120 -width 88 -height 15 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che68 \
        -in $site_3_0 -x 20 -y 30 -width 175 -height 17 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che69 \
        -in $site_3_0 -x 20 -y 60 -width 175 -height 17 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che70 \
        -in $site_3_0 -x 20 -y 90 -width 205 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che91 \
        -in $site_3_0 -x 20 -y 150 -width 105 -height 17 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab57 \
        -foreground black -text Analysis -background {#d9d9d9} -height 85 \
        -width 260 
    vTcl:DefineAlias "$top.lab57" "analysisFrame" vTcl:WidgetProc "pyxtal_main" 1
    set site_3_0 $top.lab57
    checkbutton $site_3_0.che64 \
        -activebackground {#d9d9d9} -anchor w -background {#d9d9d9} \
        -foreground {#000000} -highlightcolor black -justify left \
        -text Trajectories -variable che64 
    vTcl:DefineAlias "$site_3_0.che64" "TrajCheck" vTcl:WidgetProc "pyxtal_main" 1
    checkbutton $site_3_0.che66 \
        -activebackground {#d9d9d9} -activeforeground black -anchor w \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text Trajectories -variable che64 
    vTcl:DefineAlias "$site_3_0.che66" "TrajCheck_6" vTcl:WidgetProc "pyxtal_main" 1
    checkbutton $site_3_0.che71 \
        -activebackground {#d9d9d9} -activeforeground black -anchor w \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text {Orientational Correl. func.} -variable che64 
    vTcl:DefineAlias "$site_3_0.che71" "TrajCheck_11" vTcl:WidgetProc "pyxtal_main" 1
    checkbutton $site_3_0.che72 \
        -activebackground {#d9d9d9} -activeforeground black -anchor w \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text Trajectories -variable che64 
    vTcl:DefineAlias "$site_3_0.che72" "TrajCheck_12" vTcl:WidgetProc "pyxtal_main" 1
    place $site_3_0.che64 \
        -in $site_3_0 -x 10 -y 60 -width 155 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che66 \
        -in $site_3_0 -x 113 -y 176 -width 155 -height 17 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che71 \
        -in $site_3_0 -x 10 -y 30 -width 215 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che72 \
        -in $site_3_0 -x 445 -y 594 -width 155 -height 17 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab97 \
        -foreground black -text {Window Control} -background {#d9d9d9} \
        -height 175 -width 260 
    vTcl:DefineAlias "$top.lab97" "windowFrame" vTcl:WidgetProc "pyxtal_main" 1
    set site_3_0 $top.lab97
    checkbutton $site_3_0.che98 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text {Retain Windows} -variable che63 
    vTcl:DefineAlias "$site_3_0.che98" "RetainCheck" vTcl:WidgetProc "pyxtal_main" 1
    button $site_3_0.but99 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Go 
    vTcl:DefineAlias "$site_3_0.but99" "GoButton" vTcl:WidgetProc "pyxtal_main" 1
    button $site_3_0.but100 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Kill All 
Image Windows} 
    vTcl:DefineAlias "$site_3_0.but100" "Button1_9" vTcl:WidgetProc "pyxtal_main" 1
    place $site_3_0.che98 \
        -in $site_3_0 -x 10 -y 30 -width 119 -height 17 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but99 \
        -in $site_3_0 -x 60 -y 60 -width 128 -height 33 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but100 \
        -in $site_3_0 -x 60 -y 110 -width 128 -height 43 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab41 \
        -in $top -x 10 -y 20 -width 290 -relwidth 0 -height 245 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but43 \
        -in $top -x 460 -y 520 -width 118 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 10 -y 280 -width 290 -relwidth 0 -height 295 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but40 \
        -in $top -x 330 -y 520 -width 118 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 320 -y 20 -width 260 -relwidth 0 -height 185 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 320 -y 220 -width 260 -relwidth 0 -height 85 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab97 \
        -in $top -x 320 -y 320 -width 260 -relwidth 0 -height 175 \
        -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top39 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

