#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#    Nov 11, 2018 09:34:47 PM CET  platform: Linux

import sys
import pyxtalstats

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    stb = gui.Scrolledtext1
    for i in range(0,50):
        stb.insert("end", "Number of sandwiches: " + str(i) + "\n")
    stb.delete(1.0, "end") 
    stb.delete(1.0, "end") 
    for i in range(0,10):
        stb.insert("end", "Number of secondary sandwiches: " + str(i) + "\n")
    
def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import pyxtalstats
    pyxtalstats.vp_start_gui()




